### ISSUE TITLE
 FLOSS of opinions from v2.03 and beyond

### ISSUE THREAD

**Issue by JuPlutonic** [aldrinzigmundv/digilogtv#6] opened 2024-08-12 19:53 UTC
https://github.com/aldrinzigmundv/digilogtv/compare/v2.0.3...master#diff-a2247b9e95557e146a85f90d561962827c78c67989888f5107d20b49be5b1b02L150
This change has backported from Hypnotix?
But this channel is staying online and if you exclude it (in future) with iranian one, the app you will get will be "FLOSS app", but without FLOSS of opinions.

**Comment by aldrinzigmundv** [comment] 2024-08-15 01:33
Thank you for your message. I hope I understood you correctly. RT was removed because the link wasn’t working when I was verifying all links before the last update. I’ve now confirmed that the link is functional again. If it remains stable, it will be included in the next update.

Please rest assured that I fully support free speech and have confidence in people's ability to discern what is right and wrong. I hold the audience's judgment in high regard.

I’m also considering moving the channel list to the cloud in the future, which would allow for quicker updates without needing to go through the app stores.

If you have any other concerns, please don’t hesitate to reach out.

Thank you for your understanding.

**Comment by aldrinzigmundv** [comment] 2024-09-29 00:39
I wanted to inform you that I’m currently working on the next version of Digilog TV. Unfortunately, the RT link I have is once again not working. Unless you can provide an alternative, I won’t be able to include it in the next release.

Additionally, I’m in the process of moving the channel list outside the app bundle, which will make future channel updates faster. However, due to limited funding, we couldn’t implement an automatic system to check if IPTV links are functional.

**Comment by aldrinzigmundv** [comment] 2024-10-03 14:54
Thank you for your time! If you have any further questions or suggestions, please feel free to create a new issue. I will close this one for now due to the lack of response.

**Closed as completed by aldrinzigmundv** 2024-10-03 14:54 UTC
