### ISSUE TITLE
Add RT

### ISSUE THREAD

**Issue by aer0nix** [aldrinzigmundv/digilogtv#7] opened 2024-10-03 15:14 UTC
```
{
        "channelName": "RT English",
        "link": "https://rt-glb.rttv.com/live/rtnews/playlist.m3u8",
        "source": "iptv",
        "contactpage": "https://www.rt.com/about-us/contact-info"
    },
{
        "channelName": "RT France",
        "link": "https://rt-fra.rttv.com/live/rtfrance/playlist.m3u8",
        "source": "iptv",
        "contactpage": "https://francais.rt.com/contact"
    },
{
        "channelName": "RT DE",
        "link": "https://rt-ger.rttv.com/live/rtdeutsch/playlist.m3u8",
        "source": "iptv",
        "contactpage": "https://de.rt.com/impressum"
    },
{
        "channelName": "RT en Español",
        "link": "https://rt-esp.rttv.com/live/rtesp/playlist.m3u8",
        "source": "iptv",
        "contactpage": "https://actualidad.rt.com/acerca/contactos"
    },
```

**Comment by aldrinzigmundv** [comment] 2024-10-04 00:34
Thank you for your message. After reviewing your submission, I realize the issue seems to stem from my current location in Europe, which is affecting my access to RT’s IPTV content. It also appears that their website’s certificate isn’t working correctly in my region.

Out of respect for people's right to choose what information they consume, I’ll make it a priority to address this once I’ve finished my work today. Please be advised, however, that it still won’t work in certain regions due to local restrictions, and I will not be implementing any features in the app to bypass those laws.

I’m also considering adding geo-blocking tags to prevent similar issues in the future.

Praying for peace, my brother in God and Our Lady.

**Comment by aldrinzigmundv** [comment] 2024-10-04 20:44
I apologize for the delay; work commitments took longer than expected. I appreciate your understanding regarding the issue caused by my location in Europe.

The channel has now been added back. Please ensure you're connected to the internet before launching Digilog TV, as it updates its channel list at startup.

If you have any other issues or suggestions, feel free to open a new issue. I’m closing this one now that the issue is resolved. Just a note: Digilog TV only supports English channels, so only RT English can be added. Thank you.

**Closed as completed by aldrinzigmundv** 2024-10-04 20:44 UTC
